### GENERAL ###
server:
  port: 8080
  servlet:
    context-path: "/clientes"

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    console.settings.web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

